name: testsD4JRepair

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        test: [ 
          "fr.inria.astor.test.D4JWorkflowTestSingle#testMath2",
          "fr.inria.astor.test.D4JWorkflowTestSingle#testMath5",
          "fr.inria.astor.test.D4JWorkflowTestSingle#testMath8",
          "fr.inria.astor.test.D4JWorkflowTestSingle#testMath28",
          "fr.inria.astor.test.D4JWorkflowTestSingle#testMath40",
          "fr.inria.astor.test.D4JWorkflowTestSingle#testMath49",
          "fr.inria.astor.test.D4JWorkflowTestSingle#testMath50",
          "fr.inria.astor.test.D4JWorkflowTestSingle#testMath53",
          "fr.inria.astor.test.D4JWorkflowTestSingle#testMath70",
          "fr.inria.astor.test.D4JWorkflowTestSingle#testMath71",
          "fr.inria.astor.test.D4JWorkflowTestSingle#testMath73",
          "fr.inria.astor.test.D4JWorkflowTestSingle#testMath80",
          "fr.inria.astor.test.D4JWorkflowTestSingle#testMath81",
          "fr.inria.astor.test.D4JWorkflowTestSingle#testMath82",
          "fr.inria.astor.test.D4JWorkflowTestSingle#testMath85",
          "fr.inria.astor.test.D4JWorkflowTestSingle#testMath95",          
      ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Cache .m2
        uses: actions/cache@v2.1.6
        with:
          path: "~/.m2/repository"
          key: ${{ runner.os }}-m2

      - name: Setup JDK8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.6.0
          
      - name: removing resultsTestCases
        run: | 
         rm -rf resultsTestCases/
          

      - name: Run tests
        run: |
          mvn -ff -q clean
          mvn -ff -q test -DskipTests -DfailIfNoTests=false
          mvn -ff -q surefire:test -DfailIfNoTests=false -Dtest=${{ matrix.test }}
          
      - uses: actions/upload-artifact@v2
        with:
          name: resultsD4J
          path: resultsTestCases/

      - name: Codecov
        uses: codecov/codecov-action@v1.5.2
