name: testTwoJVM

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest


    steps:

      - name: Setup JDK8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'

      - name: Java First call with Java 8
        run: |
          echo 'test Java 8'
          java -version
          

      - name: Setup JDK11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
          
      - name: Java Second call with Java 11
        run: |
          echo 'test Java 11'
          java -version   