name: testsD4JRepair

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        test: [ 
          "fr.inria.astor.test.D4JWorkflowTest"
      ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Cache .m2
        uses: actions/cache@v2.1.6
        with:
          path: "~/.m2/repository"
          key: ${{ runner.os }}-m2

      - name: Setup JDK8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.6.0
          
      - name: removing resultsTestCases
        run: | 
         rm -rf resultsTestCases/
          

      - name: Run tests
        run: |
          mvn -ff -q clean
          mvn -ff -q test -DskipTests -DfailIfNoTests=false
          mvn -ff -q surefire:test -DfailIfNoTests=false -Dtest=${{ matrix.test }}
          
      - uses: actions/upload-artifact@v2
        with:
          name: resultsD4J
          path: resultsTestCases/

      - name: Codecov
        uses: codecov/codecov-action@v1.5.2
