name: testTwoJVM

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SRC_VERSION: $RUNNER_TEMP/java-se-7u75-ri/bin/java   

    steps:

      - name: Setup JDK8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'

      - name: Java First call with Java 8
        run: |
          echo 'test Java 8'
          java -version
          

      - name: Setup JDK11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
          
      - name: Java Second call with Java 11
        run: |
          echo 'test Java 11'
          java -version 
      - name: Install Java 7
        run: |
          wget -O $RUNNER_TEMP/java_package.tar.gz https://download.java.net/openjdk/jdk7u75/ri/openjdk-7u75-b13-linux-x64-18_dec_2014.tar.gz
          tar -xzvf  $RUNNER_TEMP/java_package.tar.gz  -C  $RUNNER_TEMP/
          ls $RUNNER_TEMP/java-se-7u75-ri      

      - name: run
        run: |
          $RUNNER_TEMP/java-se-7u75-ri/bin/java -version		
      - name: Display the path
        run: |
          import os
          print(os.environ['PATH'])
        shell: python          
      
      - name: running env var
        run: |
          import os
          print(os.getenv('SRC_VERSION'))
        shell: python
                     

# https://github.com/marketplace/actions/setup-adoptopenjdk
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '7'
          architecture: x64
          jdkFile: ${{ runner.temp }}/java_package.tar.gz
      - run: java -version